<?php
/*
 * ZeroTierCentralAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ZeroTierCentralAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Config11 implements JsonSerializable
{
    /**
     * 10-digit ZeroTier node ID [ro]
     * @var string|null $id public property
     */
    public $id;

    /**
     * 10-digit ZeroTier node ID [ro]
     * @var string|null $address public property
     */
    public $address;

    /**
     * 16-digit network ID [ro]
     * @var string|null $nwid public property
     */
    public $nwid;

    /**
     * Object type on controller ("member") [ro]
     * @var string|null $objtype public property
     */
    public $objtype;

    /**
     * True if authorized (only matters on private networks) [rw]
     * @var bool|null $authorized public property
     */
    public $authorized;

    /**
     * History of most recent authentications [ro]
     * @var array|null $authHistory public property
     */
    public $authHistory;

    /**
     * Array of IDs of capabilities assigned to this member [rw]
     * @var array|null $capabilities public property
     */
    public $capabilities;

    /**
     * Array of tuples of tag ID, tag value [rw]
     * @var array|null $tags public property
     */
    public $tags;

    /**
     * Time member record was first created [ro]
     * @var double|null $creationTime public property
     */
    public $creationTime;

    /**
     * ZeroTier public identity of member (address and public key) [ro]
     * @var string|null $identity public property
     */
    public $identity;

    /**
     * Array of IP assignments published to member [rw]
     * @var array|null $ipAssignments public property
     */
    public $ipAssignments;

    /**
     * Time member was last authorized on network [ro]
     * @var double|null $lastAuthorizedTime public property
     */
    public $lastAuthorizedTime;

    /**
     * Time member was last de-authorized on network [ro]
     * @var double|null $lastDeauthorizedTime public property
     */
    public $lastDeauthorizedTime;

    /**
     * Raw request meta-data received from member's most recent request [ro]
     * @var string|null $lastRequestMetaData public property
     */
    public $lastRequestMetaData;

    /**
     * If true do not auto-assign IPv4 or IPv6 addresses, overriding network settings [rw]
     * @var bool|null $noAutoAssignIps public property
     */
    public $noAutoAssignIps;

    /**
     * Log of most recent requests from member [ro]
     * @var array|null $recentLog public property
     */
    public $recentLog;

    /**
     * Member record revision counter [ro]
     * @var double|null $revision public property
     */
    public $revision;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $id                   Initialization value for $this->id
     * @param string $address              Initialization value for $this->address
     * @param string $nwid                 Initialization value for $this->nwid
     * @param string $objtype              Initialization value for $this->objtype
     * @param bool   $authorized           Initialization value for $this->authorized
     * @param array  $authHistory          Initialization value for $this->authHistory
     * @param array  $capabilities         Initialization value for $this->capabilities
     * @param array  $tags                 Initialization value for $this->tags
     * @param double $creationTime         Initialization value for $this->creationTime
     * @param string $identity             Initialization value for $this->identity
     * @param array  $ipAssignments        Initialization value for $this->ipAssignments
     * @param double $lastAuthorizedTime   Initialization value for $this->lastAuthorizedTime
     * @param double $lastDeauthorizedTime Initialization value for $this->lastDeauthorizedTime
     * @param string $lastRequestMetaData  Initialization value for $this->lastRequestMetaData
     * @param bool   $noAutoAssignIps      Initialization value for $this->noAutoAssignIps
     * @param array  $recentLog            Initialization value for $this->recentLog
     * @param double $revision             Initialization value for $this->revision
     */
    public function __construct()
    {
        if (17 == func_num_args()) {
            $this->id                   = func_get_arg(0);
            $this->address              = func_get_arg(1);
            $this->nwid                 = func_get_arg(2);
            $this->objtype              = func_get_arg(3);
            $this->authorized           = func_get_arg(4);
            $this->authHistory          = func_get_arg(5);
            $this->capabilities         = func_get_arg(6);
            $this->tags                 = func_get_arg(7);
            $this->creationTime         = func_get_arg(8);
            $this->identity             = func_get_arg(9);
            $this->ipAssignments        = func_get_arg(10);
            $this->lastAuthorizedTime   = func_get_arg(11);
            $this->lastDeauthorizedTime = func_get_arg(12);
            $this->lastRequestMetaData  = func_get_arg(13);
            $this->noAutoAssignIps      = func_get_arg(14);
            $this->recentLog            = func_get_arg(15);
            $this->revision             = func_get_arg(16);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                   = $this->id;
        $json['address']              = $this->address;
        $json['nwid']                 = $this->nwid;
        $json['objtype']              = $this->objtype;
        $json['authorized']           = $this->authorized;
        $json['authHistory']          = $this->authHistory;
        $json['capabilities']         = $this->capabilities;
        $json['tags']                 = $this->tags;
        $json['creationTime']         = $this->creationTime;
        $json['identity']             = $this->identity;
        $json['ipAssignments']        = $this->ipAssignments;
        $json['lastAuthorizedTime']   = $this->lastAuthorizedTime;
        $json['lastDeauthorizedTime'] = $this->lastDeauthorizedTime;
        $json['lastRequestMetaData']  = $this->lastRequestMetaData;
        $json['noAutoAssignIps']      = $this->noAutoAssignIps;
        $json['recentLog']            = $this->recentLog;
        $json['revision']             = $this->revision;

        return $json;
    }
}
