<?php
/*
 * ZeroTierCentralAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ZeroTierCentralAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Network implements JsonSerializable
{
    /**
     * 16-digit ZeroTier network ID [ro]
     * @var string|null $id public property
     */
    public $id;

    /**
     * Object type ("Network") [ro]
     * @var string|null $type public property
     */
    public $type;

    /**
     * Current system clock on server [ro]
     * @var double|null $clock public property
     */
    public $clock;

    /**
     * Arbitrary data that is stored and used by the UI [rw]
     * @var object|null $ui public property
     */
    public $ui;

    /**
     * Source code of network rule set [rw]
     * @var string|null $rulesSource public property
     */
    public $rulesSource;

    /**
     * Long description of this network [rw]
     * @var string|null $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @var Permissions|null $permissions public property
     */
    public $permissions;

    /**
     * Number of members online [ro]
     * @var double|null $onlineMemberCount public property
     */
    public $onlineMemberCount;

    /**
     * Capabilities defined in rule set by name [rw]
     * @var object|null $capabilitiesByName public property
     */
    public $capabilitiesByName;

    /**
     * Tags defined in rule set by name [rw]
     * @var object|null $tagsByName public property
     */
    public $tagsByName;

    /**
     * Circuit test this network every N milliseconds [ro]
     * @var double|null $circuitTestEvery public property
     */
    public $circuitTestEvery;

    /**
     * @todo Write general description for this property
     * @var Config|null $config public property
     */
    public $config;

    /**
     * Constructor to set initial or default values of member properties
     * @param string      $id                 Initialization value for $this->id
     * @param string      $type               Initialization value for $this->type
     * @param double      $clock              Initialization value for $this->clock
     * @param object      $ui                 Initialization value for $this->ui
     * @param string      $rulesSource        Initialization value for $this->rulesSource
     * @param string      $description        Initialization value for $this->description
     * @param Permissions $permissions        Initialization value for $this->permissions
     * @param double      $onlineMemberCount  Initialization value for $this->onlineMemberCount
     * @param object      $capabilitiesByName Initialization value for $this->capabilitiesByName
     * @param object      $tagsByName         Initialization value for $this->tagsByName
     * @param double      $circuitTestEvery   Initialization value for $this->circuitTestEvery
     * @param Config      $config             Initialization value for $this->config
     */
    public function __construct()
    {
        if (12 == func_num_args()) {
            $this->id                 = func_get_arg(0);
            $this->type               = func_get_arg(1);
            $this->clock              = func_get_arg(2);
            $this->ui                 = func_get_arg(3);
            $this->rulesSource        = func_get_arg(4);
            $this->description        = func_get_arg(5);
            $this->permissions        = func_get_arg(6);
            $this->onlineMemberCount  = func_get_arg(7);
            $this->capabilitiesByName = func_get_arg(8);
            $this->tagsByName         = func_get_arg(9);
            $this->circuitTestEvery   = func_get_arg(10);
            $this->config             = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                 = $this->id;
        $json['type']               = $this->type;
        $json['clock']              = $this->clock;
        $json['ui']                 = $this->ui;
        $json['rulesSource']        = $this->rulesSource;
        $json['description']        = $this->description;
        $json['permissions']        = $this->permissions;
        $json['onlineMemberCount']  = $this->onlineMemberCount;
        $json['capabilitiesByName'] = $this->capabilitiesByName;
        $json['tagsByName']         = $this->tagsByName;
        $json['circuitTestEvery']   = $this->circuitTestEvery;
        $json['config']             = $this->config;

        return $json;
    }
}
