<?php
/*
 * ZeroTierCentralAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ZeroTierCentralAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class User implements JsonSerializable
{
    /**
     * User ID (GUID) [ro]
     * @var string|null $id public property
     */
    public $id;

    /**
     * Object type [ro]
     * @var string|null $type public property
     */
    public $type;

    /**
     * Current system clock on server [ro]
     * @var double|null $clock public property
     */
    public $clock;

    /**
     * @todo Write general description for this property
     * @var GlobalPermissions|null $globalPermissions public property
     */
    public $globalPermissions;

    /**
     * Arbitrary data that is stored and used by the UI [rw]
     * @var object|null $ui public property
     */
    public $ui;

    /**
     * User display name [rw]
     * @var string|null $displayName public property
     */
    public $displayName;

    /**
     * User e-mail [ro]
     * @var string|null $email public property
     */
    public $email;

    /**
     * Object containing one or more authentication types and login names or IDs [ro]
     * @var object|null $auth public property
     */
    public $auth;

    /**
     * SMS telephone number for sending SMS notifications [rw]
     * @var string|null $smsNumber public property
     */
    public $smsNumber;

    /**
     * Array of API authentication tokens [rw]
     * @var array|null $tokens public property
     */
    public $tokens;

    /**
     * @todo Write general description for this property
     * @var Permissions|null $permissions public property
     */
    public $permissions;

    /**
     * Subscriptions by plan ID [ro]
     * @var object|null $subscriptions public property
     */
    public $subscriptions;

    /**
     * Constructor to set initial or default values of member properties
     * @param string            $id                Initialization value for $this->id
     * @param string            $type              Initialization value for $this->type
     * @param double            $clock             Initialization value for $this->clock
     * @param GlobalPermissions $globalPermissions Initialization value for $this->globalPermissions
     * @param object            $ui                Initialization value for $this->ui
     * @param string            $displayName       Initialization value for $this->displayName
     * @param string            $email             Initialization value for $this->email
     * @param object            $auth              Initialization value for $this->auth
     * @param string            $smsNumber         Initialization value for $this->smsNumber
     * @param array             $tokens            Initialization value for $this->tokens
     * @param Permissions       $permissions       Initialization value for $this->permissions
     * @param object            $subscriptions     Initialization value for $this->subscriptions
     */
    public function __construct()
    {
        if (12 == func_num_args()) {
            $this->id                = func_get_arg(0);
            $this->type              = func_get_arg(1);
            $this->clock             = func_get_arg(2);
            $this->globalPermissions = func_get_arg(3);
            $this->ui                = func_get_arg(4);
            $this->displayName       = func_get_arg(5);
            $this->email             = func_get_arg(6);
            $this->auth              = func_get_arg(7);
            $this->smsNumber         = func_get_arg(8);
            $this->tokens            = func_get_arg(9);
            $this->permissions       = func_get_arg(10);
            $this->subscriptions     = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                = $this->id;
        $json['type']              = $this->type;
        $json['clock']             = $this->clock;
        $json['globalPermissions'] = $this->globalPermissions;
        $json['ui']                = $this->ui;
        $json['displayName']       = $this->displayName;
        $json['email']             = $this->email;
        $json['auth']              = $this->auth;
        $json['smsNumber']         = $this->smsNumber;
        $json['tokens']            = $this->tokens;
        $json['permissions']       = $this->permissions;
        $json['subscriptions']     = $this->subscriptions;

        return $json;
    }
}
