<?php
/*
 * ZeroTierCentralAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ZeroTierCentralAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'http://localhost';

    /**
     * The OAuth 2.0 access token to be set before API calls
     * @var string
     */
    /**
     * @todo Replace the $oAuthAccessToken with an appropriate value
     */
    public static $oAuthAccessToken = 'TODO: Replace';
}
